### ISSUE TITLE
JSON response error

### ISSUE THREAD

**Issue by aptonline** [smallsco/macstodon#3]
Hi,  Finally getting around to trying Mastodon out in BasiliskII but getting the following error:

![Screenshot 2022-12-22 at 10 49 42](https://user-images.githubusercontent.com/190136/209118386-1a0f008b-e67e-4e07-8456-7fcefd451225.png)

I've added my instance (mas.to) under `ForceHttps` and also changed the `UserAgent` to `Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15` but still getting the same result.

I'm able to browse sites like `bbc.co.uk` fine with iCab and can bring up the webOne status page fine.

**Comment by Sinclair-Speccy** [comment]
You should check your WebOne config. Make sure the old user agent is commented out and the replacement isn't commented out

**Comment by aptonline** [comment]
Ok so I think I fixed it.  My `webone.conf` file was from an old install of webone and as I updated webone to the latest I needed to also align the conf file.  Connected fine :)

Within your docs however you mention adding a new user agent to `UserAgent` presumably with the `[Server]` section but on closer inspection there are a number of `UserAgent` listed.  I ended up amending 2 out of the 3 but not sure if this needed.

```
[Server]
; Server settings
; Port=Port to listen
; DefaultHostName=Proxy's host name (set to valid IP or domain name for use with/on Linux or macOS)
; Authenticate=Set if the proxy needs to be protected by "login:password" or leave blank
; OutputEncoding=Codepage for patched output content (list of available: http://localhost/!codepages/)
; HideClientErrors=Hide client connection error messages in log (for Netscape 3 PNG rejections)
; SearchInArchive=Enable searching for unavailable pages (Server Not Found or 404) in archive.org
; HideArchiveRedirect=Display archived pages just as they are still live
; ArchiveUrlSuffix=May be "fw_" to hide archive.org toolbar or "id_" to keep original links
; ShortenArchiveErrors=Enable shortening of 404s on web.archive.org to get off large scipts and images
; ArchiveDateLimit=Upper limit of date for web.archive.org archived pages
; SecurityProtocols=Forcely set SSL/TLS protocols that can be used for retrieving web content
; ValidateCertificates=Break network operations when the remote TLS certificate is bad
; UpperProxy=Another proxy server, used by WebOne to connect to Internet (optional)
UserAgent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15
; TemporaryDirectory=Directory which should be used for temporary files (%TEMP%, $TEMP or any other)
; LogFile=Path to server log file. To use a log file without erasing, use AppendLogFile instead
; DisplayStatusPage=Set status page display style (no, short, full)
Port=8080
DefaultHostName=192.168.1.12
;Authenticate=login:password
OutputEncoding=AsIs
;OutputEncoding=Windows
;OutputEncoding=DOS
;OutputEncoding=Apple
HideClientErrors=yes
SearchInArchive=yes
HideArchiveRedirect=yes
ArchiveUrlSuffix=fw_
ShortenArchiveErrors=yes
;ArchiveDateLimit=20070101
;SecurityProtocols=4032
ValidateCertificates=yes
;UpperProxy=http://corporateproxyserver:80/
;UpperProxy=no
UserAgent=%Original% WebOne/%WOVer%
UserAgent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15
TemporaryDirectory=%TEMP%
;LogFile=%SYSLOGDIR%/webone.log
AppendLogFile=%SYSLOGDIR%/webone.log
DisplayStatusPage=short
```

**Comment by Sinclair-Speccy** [comment]
Get rid of `UserAgent=%Original% WebOne/%WOVer%` as I am pretty sure that causes problems. I am not sure if this is okay to post yet but I made a guide on this a while ago [here](https://sinclair-speccy.github.io/The-Mainframe/macstodon.html). You should just scroll down to the WebOne part

**Comment by aptonline** [comment]
What about the other UserAgent further up the config, surely they overwrite each other and only one is needed?

**Comment by Sinclair-Speccy** [comment]
Those should be fine as I left them as they are. This reminds me I need to add a comment section to my guides 😅

**Comment by smallsco** [comment]
So, any line with a semicolon in front is commented out and can be ignored. There should only be one user-agent that is left uncommented, which will be the active one - it may be easier to remove the commented out ones entirely.

I'm not sure what happens if multiple user-agent lines are uncommented, whether it takes the first, last, or picks one randomly. Either way, you should only have one of them uncommented.

**Comment by aptonline** [comment]
I think this is an issue with default `webone.conf` then as it lists multiple `UserAgent` entries under server. I’ll raise an issue there 👍.
