### ISSUE TITLE
Created a folder icon for Macstodon

### ISSUE THREAD

**Issue by eisnerguy1** [smallsco/macstodon#4]
So, I created a quick icon for Macstodon
![Macstodon ƒ](https://user-images.githubusercontent.com/3295271/209427960-ea2f4f6a-a878-479a-bfb7-edd1b476c4af.png)

I've included a sit.hqx file that has an icon made with [Iconographer](https://www.mscape.com) and a folder with the icon pasted on it:
https://www.mediafire.com/file/4pgr1p2bgb5at43/Macstodon_Folder_Icons.sit.hqx/file

Feel free to use as I did not create the original Macstodon icon, just used it for the folder icon. But, if you want to mention me, I'm [@eisnerguy1@mastodon.social](https://mastodon.social/@eisnerguy1).

**Comment by smallsco** [comment]
Thank you, I will start using this in the next major release (0.5)
