### ISSUE TITLE
Updated Macstodon folder icon

### ISSUE THREAD

**Issue by eisnerguy1** [smallsco/macstodon#5]
I updated the folder icon to include a proper 16x16 icon
<img src="https://user-images.githubusercontent.com/3295271/209744028-afb4e385-9c6d-4243-8c9b-91efe76103b0.png" width=484>
https://www.mediafire.com/file/2dprbygunznf4g7/Macstodon_%25C6%2592_Icons_2.sit.hqx/file

**Comment by smallsco** [comment]
Thank you! I'll start using this with the 0.5 release.
