### ISSUE TITLE
Trouble Authenticating

### ISSUE THREAD

**Issue by miakizz** [smallsco/macstodon#8]
Hello!
I understand this project is for fun, but I thought I post up this ticket just to see if anyone else has run into this.
Something in my setup seems to be disagreeing with WebOne. Whenever I put in my instance URL, the program gets stuck on the "Fetching Data..."  progress bar with the following in the proxy console
```
17.12.2023 17:06:21.181+98943        >GET http://tacobelllabs.net/api/v1/accounts/verify_credentials (10.0.0.193)
17.12.2023 17:06:21.181+267147  >Downloading content...
17.12.2023 17:06:21.181+1851538  200 OK. Body ?K of application/json; charset=utf-8 [Text].
17.12.2023 17:06:21.181+1878030 <Done (connection close).
```
If I close the proxy, the program immediately continues to the screen with the auth URL. Pasting in the response code and trying to log in causes it to hang again. Stopping the proxy fixes the hang, but then the program crashes due to it not being able to reach the proxy for the next thing it's fetching. I've tried this on an iMac G3 running System 9, and an iBook running in Classic, with WebOne running on Linux and an ARM Mac. I've tried different user agents, and forcing HTTPS, and multiple Mastodon instances in case mine was doing something weird. Both clients can access the server through a browser, so I know the proxy somewhat works. 

Has anyone run into something similar?

**Comment by smallsco** [comment]
Hm. I haven't seen this specific issue before, and you've already tried most of the things that I would suggest.

The one thing I can think of that you didn't mention - what version of WebOne are you running? I'm running 0.15.3 - if you're running a later version, perhaps there is something that breaks compatibility?

My webone `my.conf` looks like this - I haven't made any changes to the default `webone.conf`:
```
[Server]
UserAgent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.2 Safari/605.1.15

[ForceHttps]
oldbytes.space
botsin.space
bitbang.social
urusai.social
```

Another possibility is that something in a recent Mastodon version update is causing problems. Are all the instances that you tried running the same Mastodon version?

**Comment by miakizz** [comment]
Using WebOne 0.15.3 resolved the issue!

**Comment by smallsco** [comment]
I've fixed this on the Macstodon side with today's release of version 1.1.2, which adds compatibility with WebOne 0.16 and above.
